 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  nextqa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /tmp2/adnchao/nextqa/seliva_nextqa_train.json
          storage: /tmp2/adnchao/nextqa/seliva_nextqa_train.json
        val:
          url: /tmp2/adnchao/nextqa/seliva_nextqa_val.json
          storage: /tmp2/adnchao/nextqa/seliva_nextqa_val.json
        test:
          url: /tmp2/adnchao/nextqa/seliva_nextqa_val.json
          storage: /tmp2/adnchao/nextqa/seliva_nextqa_val.json
      videos:
        storage: /tmp2/adnchao/NExTVideo/
