 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
datasets:
  tim_bc: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_exclude_20_trope_total_5_movie.json
          storage: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_exclude_20_trope_total_5_movie.json
        val:
          url: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_20_movie_20_trope_eval.json
          storage: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_20_movie_20_trope_eval.json
          # url: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_5_plot_20_trope.json
          # storage: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_5_plot_20_trope.json
        test:
          url: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_5_plot_20_trope.json
          storage: /tmp2/adnchao/TropeVLM/tropes/trope_bc_with_definition_subset_5_plot_20_trope.json
      videos:
        storage: /project/mira/dataset/MovieNet/videos/
